services:
  - type: web
    name: ekb-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ekb-database
          property: connectionString
